### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by ramosslyz** [hannob/smtpsmug#4]
I want to test this tool for our company but it keep giving this :
python3 smtpsmug2.py mail.mycompany.com -u user1@mycompany.com -p mycompany2! --port 25 --tls -t user2@mycompany.com

Namespace(host='mail.mycompany.com', mailfrom='user1@mycompany.com', to='user2@mycompany.com', ehlo=None, user='user1@mycompany.com', password='mycompany2!', tls=True, port=25, test='lflf', list_tests=False)
Traceback (most recent call last):
  File "/home/user/smtpsmug2.py", line 186, in <module>
    main()
  File "/home/user/smtpsmug2.py", line 173, in main
    psock.connect((args.host, port))
TimeoutError: timed out

**Comment by hannob** [comment]
This looks to me that your smtp server simply does not answer (timeout). I'm almost certain the problem is with the server. Do you maybe run the test from an IP space that the server blocks? Can you do a manual SMTP connection to that server via netcat? ("nc -C [hostname] 25", then try "EHLO test").

There's little I can do without knowing the server hostname. If you can share that, I can have a look.

**Comment by hannob** [comment]
Can't do anything without further info, please re-open if you can provide that.
